### ISSUE TITLE
HA front end issues

### ISSUE THREAD

**Issue by Spitfire69** [BigFoot2020/daikin_residential_brp069a62#1]
Hello,

I have tested this integration on a system that use a thermostat to control the temperture from my Daikin MonoBloc connected to the BRP069A62 and it seems to work fine however I have seen some frontend issues. I guess the slowness of connecting to the Daikin backend possibly could be an issue in some of the points below.

1. The standard HA thermostat card does not show the indoor temperature but the output from the heatpump.
2. It's unclear what the icons in the  thermostat means since they do not reflect the status fully (ie the on/off symbol should be lightened up shouldn't it? or is it only on when the pump is producing heat?).
3. If you press the thermostat buttons (fire and on/off) it is possible to turn off the heatpump but turning it on the way doesn't work or? 
4. The thermostat heating type does not seem to reflect the current heating type ie off, heat, powerful mode at least not for the powerful mode which I turned on and off with the switch above the thermostat card.
5. The water_heater.altherma shows the setpoint as main info not the current temperature.

Keep up the good work! :)

![image](https://user-images.githubusercontent.com/28536879/147467200-85f85a88-2c85-4b43-a553-24b18ab8f6aa.png)

**Comment by BigFoot2020** [comment]
Part of the slowness is built into the component: it connects to Daikin Cloud every 15 seconds, so it's not instant. Also other part of slowness is your heat pump connecting to Daikin Cloud and getting updated settings (or updating attribute values). This is one of the reasons I'm currently looking into possibility to connect to LAN Adapter locally via WebSockets.

1. It would be simple change in code to show indoor temp there, but ... Since I don't have external (room) thermostat connected to heat pump, indoor temp for me is in the heat pump in basement (almost constant), which does not give me much info. My heatpump is in weather-dependant mode, so I was more interested in seeing current setpoint. Probably would be possible to decide which temp to show based on control mode?
2. Buttons select operation mode of heatpump. I have option to choose between Auto, Cooling, Heating and Off. Current mode is highlighted. Maybe I should not have added "Off" mode there as it is separate switch?
3. These are not push buttons, but select buttons (only one can be active). So if you want to turn off heat pump, you click on "Off" mode, to turn pump on again, click on "Heat" mode. And yes, delay causes issues here and it is confusing, but it seemed to be easiest way to get setpoint changing working and that was main goal. Should add screenshot and explanation to docs.
4. Powerful mode is for Water Heater only, no direct relation to Climate entry, so I kept it out of there. Thermostat card should still show if room heating is on or off (although with delay).
5. This is how Water Heater component in Home assistant is designed. Main purpose of this entity is to be able to change DHW setpoint. You can also change operatin mode to Powerful (named Perfomance in Water Heater card, again coming form HA component).

**Comment by MikeRolefes** [comment]
Hello,

Thanks for the good work!

what I miss regarding to the picture above is the DHW settings and water temperatures. 

those are not visible in my HA. 

I just recently added an DHW system to my Daikin heat pump.

am i doing anything wrong?

**Comment by vincentlieubeau** [comment]
Hello BigFoot,

Thanks for your super nice development ! I have a Diakin altherma Heat Pump with BRP069A62 network adapter, i have installed your integration and it's working well.

Like Spitfire69, i would really enjoy seeing the Altherma Inside Temperature, instead of the heat pump output, as main indicator in the thermostat card. Can you give me the main guidelines to make the modification by myself, i suppose it must be in the custom component files. I am not very at ease with Home assistant programing but i do other king of programing (php, javascript...) so i should be able to make it if you help me a little bit. Can you tell me wich file i have to edit ? Which variables are involved and approximately where in the code i should do the modification ?

Big thanks in advance !

Vincent

**Comment by BigFoot2020** [comment]
To change temperature shown in thermostat card, in HA Config custom_components\daikin_residential_brp069a62\climate.py
Line 127: `return self._device.leavingWater_temperature`
Replace with: `return self._device.inside_temperature`

Edit: wrong line number

**Comment by vincentlieubeau** [comment]
Wouah !! It's working ! You're the boss, thanks !

**Comment by BigFoot2020** [comment]
In case interested [Daikin Residential for Altherma](https://github.com/speleolontra/daikin_residential_altherma/) now supports BRP069A62. You may want to try if it also supports your system without manual modifications. In case not, you should open new issue ont that repository.
