### ISSUE TITLE
Altherma 3 Geo EGSAX06DA9W Geothermal heat pump

### ISSUE THREAD

**Issue by thecem** [BigFoot2020/daikin_residential_brp069a62#10]
Hi,
thank your for the integration. We using it with Altherma 3 Geo EGSAX06DA9W geothermal heat pump with the onecta app.
Is there a documentation of the API of Daikin?
How to log in with a browser in a easy way into the cloud to see wich parameter will be available?

Could we add additional information like Error State, Alarm, all Paramter in Info screen?

Are the values for working fluid empetratur, heatingsystem pressure, compressor restarts, compressor state and elctrical heatingrod available?

Thanks a lot!

**Comment by BigFoot2020** [comment]
Hello!

There is no public documentation of Daikin cloud API. As far as I know there is no way to use that service via browser. Only way to access it is using ONECTA app. Everything we have and know is achieved by sniffing and reverse engineering that (or previous) app. This basically means that anything that you see in app could probably be added also to HA integration.

As stated in other issues, I am not planning to do any further development for this integration (other than some basic fixes in case needed), since I don't have enough knowledge nor skills to do it in a way that makes sense to me. However I'm willing to help you (or anyone else interested) to get started.

**Comment by thecem** [comment]
Thanks 🙏! So I will do some sniffing to see what could be additional extracted..

**Comment by jwillemsen** [comment]
Have you tried https://github.com/speleolontra/daikin_residential_altherma?
