### ISSUE TITLE
Differences with daikin_residential_altherma?

### ISSUE THREAD

**Issue by jwillemsen** [BigFoot2020/daikin_residential_brp069a62#13]
I can only see the initial import, but I wonder what the differences are compared to the https://github.com/speleolontra/daikin_residential_altherma integration? I have done a lot of improvements to that one and I am interested to learn what is special for the BRP069A62, as far as I can tell it also uses the onecta app and the daikin cloud? 

At some point I hope we can have one daikin_residential integration supporting various models.

**Comment by BigFoot2020** [comment]
The main difference is naming of Management Points in returned JSON, you can compare const.py on both repos to see this.

Since "Daikin Residential Altherma" integration simply did not recognize my BRP069A62, I started to modify it and finally got it working. I was not able to figure out how to compine these (way out of my league), so I created separate repo to shar with others in same position and in hope that someone would be albe to combine these (and also maybe with original https://github.com/rospogrigio/daikin_residential).

I would be happy to support in any way that I can with comining these, but in my understanding this is not an easy task. You can read my comments on other issues here, a lot of them are on similar topics.

**Comment by jwillemsen** [comment]
Can you maybe attach a json from your device here, that is much easier to compare.

**Comment by BigFoot2020** [comment]
Here it is: [daikin_puredata.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11038696/daikin_puredata.json.txt)

**Comment by jwillemsen** [comment]
Thanks, looks you have a separate `targetTemperature` which looks similar to `temperatureControl`. Also you have no energy values, but this doesn't look to be the full export. I think daikin_residential_altherma got improved, but no idea whether it supports your device also. Maybe add the diagnostics support (see https://github.com/speleolontra/daikin_residential_altherma/pull/37) so that the export is the same? Maybe at some point you can try daikin_residential_altherma and let me know the results/logs?

**Comment by BigFoot2020** [comment]
This is full JSON that I get when doing "self.doBearerRequest("/v1/gateway-devices")" (see daikin_api.py starting line 475). 
I have not removed export and implemented diagnostics. I can try to implement this and see what would be the differences.
Note that I don't have energy values in Onecta app also, either my heat-pump or BRP069A62 simply do not support this.

**Comment by BigFoot2020** [comment]
Additionally, I am still pretty sure that there is no point to try again, since Management Point names are still defined as constants and based on embeddedId's, so my device will not be found. 
When parsing JSON "daikin_residential_altherma" will try to find MP with name MP_GATEWAY = "gateway", which is not present in my JSON as for me MP_GATEWAY = "0" #"gateway".
To combine these 2, MPs  would have to be dynamic, detected by code based on "managementPointType".

**Comment by jwillemsen** [comment]
Looks managementPointType is the best solution, at some point I want to rework the constants, get rid of them, see https://github.com/speleolontra/daikin_residential_altherma/issues/86. I will keep your remark in mind

**Comment by jwillemsen** [comment]
For daikin_residential_altherma I probably need to change `MP_CLIMATE` to `climateControl` and store the `managementPointType` instead of the `embeddedId`, that should solve your remark, let try that asap.

**Comment by jwillemsen** [comment]
@BigFoot2020, can you maybe try a test branch where I used `managementPointType`, that works for my Altherma at least, see https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-embeddedid, curious whether it solves your issue with your altherma version

**Comment by BigFoot2020** [comment]
That was it, basically one minor change :-) and it works.
Did not expect it to be that simple. First thought was, how did I not think of this before. Kudos to You for figuring this out!

Other notes: you cannot have both integrations on one HA insance, names are conflicting, so will need to do some cleanup on my test HA. Will try to verify if everything else works as expected.

Diagnostics output, in case you want to compare:
[daikin_residential_altherma-xxx-Daikin Climate-xxx.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11039488/daikin_residential_altherma-xxx-Daikin.Climate-xxx.json.txt)

**Comment by jwillemsen** [comment]
Ok, great, so I can merge my branch and make a new release, after that you can switch to the daikin_residential_altherma and archive this project, correct?

**Comment by BigFoot2020** [comment]
Basically yes.

**Comment by jwillemsen** [comment]
New release available, see https://github.com/speleolontra/daikin_residential_altherma/releases/tag/v2.5.3, thanks for your json and tests!

**Comment by BigFoot2020** [comment]
Did some further testing and there are some issues. Shoud I open these under daikin_residential_altherma?
Main one: setting values does not work, response from Daikin is "BEARER RESPONSE CODE: 404". Probably because it expects embeddedId in that request, not managementPointType (as these are not same for me).

**Comment by jwillemsen** [comment]
Yes, please open it there. I reverted the change there, need to find a clean solution for this

**Comment by jwillemsen** [comment]
Can you test https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-embeddedid2? In that branch I made a change to copy all values from the daikin json to the internal data and when setting a value I convert the management point type back to the embeddedid

**Comment by BigFoot2020** [comment]
With this version setting values works, so essential functionality is there now.
One big difference that when I change something, my integration keeps that in HA, yours does not until next update.
For example, when I click climate Off button, there would be no reaction in "daikin_residential_altherma".
I have this in my daikin_api.py (+ related things in other files):
```
        # The Daikin cloud returns old settings if queried with a GET
        # immediately after a PATCH request. Se we use this attribute
        # to skip the first GET if a PATCH request has just been executed.
        self._just_updated = False

        # The following lock is used to serialize http requests to Daikin cloud
        # to prevent receiving old settings while a PATCH is ongoing.
        self._cloud_lock = asyncio.Lock()

```

There are some errors during initalization and MAC/Serial are not read from JSON. As agreed I will create separate issues for these.

**Comment by jwillemsen** [comment]
Thanks for testing! Feel free to open separate issues or pull requests for the things you see, that way we can improve the integration step by step. At some point I want to rework it so that there is just one daikin_residential integration that supports Altherma 3 and the airco units

**Comment by jwillemsen** [comment]
Just had a look, backported https://github.com/speleolontra/daikin_residential_altherma/pull/134, can you test those for me?

**Comment by BigFoot2020** [comment]
Yes, that seems to work.

**Comment by jwillemsen** [comment]
Thanks!
