### ISSUE TITLE
BRP069A62 (Altherma 3) doesn't seem to configure correctly

### ISSUE THREAD

**Issue by clovissix** [BigFoot2020/daikin_residential_brp069a62#3]
Hi,

I have an Altherma 3 water heatpump, but when I tried this plugin I get the following in the logs. Any idea?
```2022-01-24 23:03:34 WARNING (MainThread) [custom_components.daikin_residential_brp069a62.daikin_api] Device with ID '0b5a6741-238c-4d36-a5c6-6c1e56132a60' is filtered out```

After configuring it lists no entities.

**Comment by clovissix** [comment]
This error originated from a custom integration.

Logger: custom_components.daikin_residential_brp069a62.daikin_api
Source: custom_components/daikin_residential_brp069a62/daikin_api.py:499
Integration: Daikin Residential Controller for BRP069A62 (documentation, issues)
First occurred: 23:48:37 (5 occurrences)
Last logged: 23:48:37

Device with ID '0b5a6741-238c-4d36-a5c6-6c1e56132a60' is filtered out
Device with ID '6eb517a8-6060-4474-b2bc-fa45b50aa192' is filtered out
Device with ID '9b624865-626c-42d5-b208-90055e3b2c81' is filtered out
Device with ID 'a2d3693f-9cf5-4113-b039-254bc1ea71dd' is filtered out
Device with ID 'f1318b99-dae3-47de-9fa3-c2ea14b4e02f' is filtered out

**Comment by BigFoot2020** [comment]
Hello!

This warning is shown when integration is not able to parse device model info from Daikin Residential Cloud data. Would happend for devices other than BRP069A61/2 (that's why there are several different integrations for Daikin Residential).

Just to make sure that we cover all the basics: You do have BRP069A61/2 LAN adapter connected to your heat pump?
And you can control your Altherma heat pump via Daikin Residential Controller app?

**Comment by clovissix** [comment]
Does this plugin generate daikin_puredata.json?
I can see all values for the Altherma heatpump in there.

There is no external LAN adapter anymore. The newer versions had it built-in I suppose. At least not like with my Daikin Aircos who had an external LAN adapter. Maybe they have added it within the housing of the Altherma.

I do have access via Daikin Residential Controller. That's also why I have the data of the heat pump within daikin_puredata.json.
[daikin_puredata.zip](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/7932462/daikin_puredata.zip)

**Comment by BigFoot2020** [comment]
This integration is specifically for BRP069A62. It works also with BRP069A61, since they are almost identical devices. It does not work with newer (built-in) versions, because data structure in json is different. That was the main reason why I needed to create separate integration. 

You should try integration from Speleolontra for "daikin_residential_altherma" [https://github.com/speleolontra/daikin_residential_altherma], that should work for your heat pump.

Also you may try original "Daikin Residential" integration from Rospogrigio for Daikin Aircos (if you are not doing that already).
