### ISSUE TITLE
Energy Consumption Data

### ISSUE THREAD

**Issue by onix62** [BigFoot2020/daikin_residential_brp069a62#7]
How can I read out Energy Consumption Data?

**Comment by BigFoot2020** [comment]
Since my own device does not support reading Energy Consuption Data, I have removed all related parts from this integration (to be able to get it working).  Currently I'm using ESPAlthema and Shelly to monitor energy consumption.

You may want to take a look at Speleolontra's "daikin_residential_altherma", that should have Energy reading. If you have BRP069A62, the you probably would need to build your own custom componend based on both of these.

Some questions that may help you get started:
Which device you have (Heat pump and adapter)? 
Are you using Daikin Residential Cloud (via Daikin Onecta app)?
Do you see Energy Consumption in app?
If you get integration working, you should check content of "daikin_puredata.json" for energy data.

**Comment by jwillemsen** [comment]
Related to https://github.com/speleolontra/daikin_residential_altherma/issues/53

**Comment by onix62** [comment]
EGSAX06DA9W
BRP069A61
I use the Onecta app
 I see the Energie  Consumption in the app and in daikin_puredata.json

**Comment by BigFoot2020** [comment]
In case interested [Daikin Residential for Altherma](https://github.com/speleolontra/daikin_residential_altherma/) should now support BRP069A61 and has Energy Consumption sensors. Please try that.
